# Starter pipeline
- task: VSBuild@1
  inputs:
    solution: 'ImplicitModeling.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'Release'
    clean: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
